### PR TITLE
YAML: Switch to ruamel.yaml

### PR DESCRIPTION
**Pull request by nijel**
- This allows us to remove majority of custom code around preserving
  order of keys
- It supports YAML 1.2 which supports yes/no as keys (see #3695)

### CODE REVIEW

**Comment by nijel** [comment]
I'm not sure what to do with the `test_no_duplicates` test - it starts with an invalid YAML document and assumes the tool somehow handles that, what is IMHO wrong...

**Comment by unho** [comment]
Nice PR. This will allow us to circumvent the warning we are having with PyYaml being insecure.

Regarding the test, if it is there it is probably because in the real world we've found some YAML with duplicate keys. The question is, how does ruamel.yaml handle this?

**Comment by nijel** [comment]
It throws an `DuplicateKeyError` error as the file violates the YAML specification, it can be seen here https://travis-ci.org/translate/translate/jobs/483580011#L990

**Comment by nijel** [comment]
Looking at it again, it can be enabled for now, but I'm not sure this is a good idea, also see https://yaml.readthedocs.io/en/latest/api.html#duplicate-keys

**Comment by unho** [comment]
Ok, we can forbid duplicate keys for now. I we should keep the test because maybe in the future it is necessary to enable back the duplicate keys.

lgtm

**Comment by nijel** [comment]
Thanks for review.

**Pull request merged**
