### PR TITLE
Add new language plurals

### PR DESCRIPTION
**Pull request by unho**
From http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html

@dwaynebailey Since this impacts Pootle it might not be a good idea to add these languages.

References https://github.com/translate/translate/issues/3263

Related PR: https://github.com/translate/l10n-guide/pull/32

### CODE REVIEW

**Comment by dwaynebailey** [comment]
@unho I think you're missing the point here.  The errors exist for the same reason that I raised the issue about HTML quality check pages where you wanted to dump in all checks without generating them from the check comments.  That is that if they are not autogenerated then you will always end up with a mess.  If you want to fix this then please do it properly, with one place to make all errors. I'm a bit sad actually that you didn't pick this up since we talked about the same type of issue only last week.

I'm not sure why we wouldn't want to add these languages i.t.o the comment re Pootle.

**Comment by unho** [comment]
@dwaynebailey TTK is the place where plurals are kept. But there is also a table on the localization guide. I don't see how we can create the plural rules from the other project without coupling the former with the other project.

I was trying to say that if those languages are not considered to be core, we might want not to add them so we don't overcrowd Pootle UI. But given the live filtering we now have in Pootle UI that shouldn't be a big problem.

**Comment by dwaynebailey** [comment]
@unho coupling is the least of evils, it is then autogenerated from the toolkit which would be the right thing to do.  Otherwise you are defending the pain of coupling by the definate pain of these things always being out of sync and needing multiple place to configure.

I'm not concerned about overcrowding Pootle UI.  My personal view is that we should actually have all ISO languages in Pootle in the long term.

**Comment by unho** [comment]
@dwaynebailey Since you say it should be autogenerated from the toolkit, and this is a PR for the toolkit, I am going to take that as a gtm.

**Comment by dwaynebailey** [comment]
@unho yip gtm

**Pull request merged**
