### PR TITLE
Add storage for nested JSON files

### PR DESCRIPTION
**Pull request by nijel**

### CODE REVIEW

**Comment by unho** [comment]
lgtm. @nijel I am landing it since I need to merge something else quite soon.

**Comment by nijel** [comment]
Thanks!

**Comment by wichert** [comment]
@unho Are you planning a new release with this change? I'ld like to use this feature, but would prefer not have to make a private release.

**Comment by unho** [comment]
@wichert A new release has just been published.

**Comment by wichert** [comment]
Thanks!

**Pull request merged**
