### PR TITLE
Add support to convert .Net Resource (.resx) files - resx2po and po2resx

### PR DESCRIPTION
**Pull request by sjhale**
Adding support for .Net Resource (.resx) files, which resolves issue #396.

### CODE REVIEW

**Comment by jleclanche** [comment]
Travis issues aside, this looks pretty exhaustive. A quick review does not bring up any code issues.

Can you make sure the files all end with a newline please? And please squash the docs and style fixes into the relevant commits with `git rebase -i` :)

@dwaynebailey @unho ping for extra review, gtm on my side.

**Comment by sjhale** [comment]
Hi @jleclanche 

Thanks for such a quick response! Sorry about the multiple commits - I'm quite new to Git. I will attempt a rebase to clear it up and I'll correct any files which don't end in a newline too. 

Thanks!

**Comment by jleclanche** [comment]
This can help: https://help.github.com/articles/about-git-rebase/

**Comment by sjhale** [comment]
Here are some sample .resx files (en-GB and az-AZ) for testing purposes: https://www.dropbox.com/sh/gv7du208kpckb7k/AADGqaXs25_RZYn8tALW2L1-a?dl=0

Example commands: 

    resx2po -i \resx -o \po
    po2resx -i \po -o \resx -t \resx\resource.en-gb.resx

**Comment by dwaynebailey** [comment]
@sjhale I'm busy doing a quick review, thanks for this effort it's a nice addition to the tool.

I think you might have forgotten to add the resx2po and po2resx helpers to the commits.  I'll post any other issues I find as I go.

**Comment by dwaynebailey** [comment]
@sjhale I landed what you had, this is nice work.  I tested using your supplied .resx files, thanks that helped a lot.

The issues I found and I'm happy to fix them though you can also:

1. Missing wrapper scripts for ``resx2po`` and ``po2resx`` see e.g. ``translate/convert/ical2po``
2. Missing copyright headers - we're going to revise these soon anyway but for now how would you like to be credited e.g. SJ Hale, fullname version or some company.
3. Missing resx2po and po2resx in setup.py
4. Possibly an error in encoding headers in one of the test files.

Thanks again, great work.  I'll leave this here for now in case you want to fix those issues yourself (which I'd appreciate ;) but ping me otherwise.

**Comment by sjhale** [comment]
Hi @dwaynebailey 

Thanks for your feedback! I'm more than happy to fix the issues you found :) I'll do that now and get back to you if I have any questions :)

**Comment by sjhale** [comment]
Just a quick note to say I think I've resolved the issues you spotted above in #3243.

**Pull request merged**
