### PR TITLE
Slovenian plural form corrected

### PR DESCRIPTION
**Pull request by beernarrd**
Corrected plural form, see  #3263.

### CODE REVIEW

**Comment by beernarrd** [comment]
Hello, any wish to have this corrected? If not, virtaal cannot be used for slovenian translations at all.

**Comment by jleclanche** [comment]
lgtm. @unho @dwaynebailey can this be merged?

**Comment by dwaynebailey** [comment]
@beernarrd can you point to an authority on the Slovenian plural form please.  IIRC Slovenian teams couldn't quite decide which form is correct, and based on your fix its simply a matter of ordering.  It isn't a missing form or a miscalculation.  I'd like to have it correct, just like you, but can you please point to some authority or consensus.

**Comment by beernarrd** [comment]
It's a historical issue and practical issue.
The oldest citation I can find is in an article from P. Peterlin 2001 in computer magazine Monitor: http://web.archive.org/web/20060507045614/http://old_www.lugos.si/arhiv/prispevki/gettext/

The practical thing is, that msgid[n] index equals the number for which the plural is used:
msgid[1] corresponds to 1 apple, msgid[2] to two apples and msgid[0] to zero apples which is very straightforward to remember. Otherwise the translation is prone to mistake.

The authority could be: http://localization-guide.readthedocs.org/en/latest/l10n/pluralforms.html
or https://l10n.gnome.org/teams/sl/ (see plural forms under the table).
Consensus can be found on slovenian linux users group translation instructions https://wiki.lugos.si/slovenjenje:pravila#mnozinske_oblike .

If virtaal overwrites this plural forms string in an existing translation file, the resulting translation has shifted number forms.

**Comment by jleclanche** [comment]
@dwaynebailey If we don't have a good reasoning behind our *current* plural form this is better than anything we got.

**Comment by dwaynebailey** [comment]
@jleclanche yeah I agree. The reason I ask is from my historic recollections as well as to know that when someone asks they do have data to backup their position as @beernarrd has provided.  So gtm from my side.

**Comment by dwaynebailey** [comment]
Landed in 15569182e0f6082551ab53a6eed4d46c66a0e045 only realise now this has been languishing since May @beernarrd sorry about that!

**Pull request closed without merging**
