### PR TITLE
More fixes to Gaia plurals

### PR DESCRIPTION
**Pull request by khaledhosny**
Various fixed to Gaia plurals support, bringing it to a usable state.

### CODE REVIEW

**Comment by unho** [comment]
@khaledhosny @dwaynebailey Is it this ok to be merged or is there any additional work still to be done?

**Comment by unho** [comment]
@khaledhosny @dwaynebailey Which is the status for this PR?

**Comment by khaledhosny** [comment]
Since Gaia is no more, I think this PR should be closed.

**Comment by unho** [comment]
Closing per the previous comment.

**Pull request closed without merging**
