### PR TITLE
pocount: prevent infinite loop if space is missing

### PR DESCRIPTION
**Pull request by Jibec**
fix: #4232

### CODE REVIEW

**Comment by Jibec** [comment]
sorry, but I have no idea how to write the unit test!

**Comment by nijel** [comment]
I still think that translate-toolkit should fail on parsing invalid files and not treat invalid syntax lines as comments (what I guess will happen here).

**Comment by Jibec** [comment]
I know how to prevent failure and continue, but not really how to properly raise an error.

When processing 200 000 po files, I just would like to prevent an endless loop.

By the way, when patching Translate, I have no idea how to activate some debug level. Would you mind documenting it somewhere?

Why should it fail when a comment doesn't have the correct format and I want to get translation statistics? May it inpact the result?

**Comment by nijel** [comment]
There is no logging inside the po parser, so there is nothing to enable, sorry.

I've made fix that will raise an error in https://github.com/translate/translate/pull/4235

**Pull request closed without merging**
