### PR TITLE
pocount: csv header in one line

### PR DESCRIPTION
**Pull request by zmlpjuran**
pocount csv header is now in one line, easy to import

### CODE REVIEW

**Comment by zmlpjuran** [comment]
fix for issue #3444

**Comment by zmlpjuran** [comment]
uff, how can I fix file permissions for the test script?
test_pocount_po_csv.sh ... tests/cli/run_tests.sh: line 7: ./test_pocount_po_csv.sh: Permission denied

**Comment by dwaynebailey** [comment]
@zmlpjuran nice fix, thanks for the contribution and doubly thanks for the tests.

**Comment by zmlpjuran** [comment]
you are welcome

**Pull request merged**
