### PR TITLE
Fix for #3672: Always URL-encode keys

### PR DESCRIPTION
**Pull request by alemangui**
Index lookups always decode them
Spaces are not the only characters requiring escaping (at least '+' needs it)

### CODE REVIEW

**Comment by unho** [comment]
The change looks ok. But it makes several tests to fail. Can you please adjust those tests too?

**Comment by nijel** [comment]
It seems that this breaks html2po conversion (the getlocations returns encoded string there), can you please look into that?

Also the urlencoding is way too aggressive here, certainly at least some chars do not have to be urlencoded (looking at the tests at least ```()/:```), I've tried to address this in https://github.com/translate/translate/pull/3676.

**Comment by alemangui** [comment]
@andreistefan87 @raphael-wb thoughts?

**Comment by unho** [comment]
@nijel I don't think #3676 fully fixes the issue outlined in this PR description.

**Comment by nijel** [comment]
I don't think as well, it addresses just the too much of escaping this PR produces for most of the cases. Still this is IMHO valid patch (once the tests pass).

**Comment by alemangui** [comment]
Here are a couple commits to update the PR to latest master and fix the remaining tests. 

FYI @andreistefan87 @raphael-wb

**Comment by unho** [comment]
Landed the changes in this PR. Thanks for the contribution.

**Pull request closed without merging**
