### PR TITLE
fix #3239 odf2xliff doesn't extract all the text

### LINKED ISSUE #3239: odf2xliff doesn't extract all the text
i use 1.12 (had problems installing 1.13rc on osx)

```
odf2xliff test.odt test.xlf
```
creates xliff files with only one translation unit containing the title (Chile)
test.odt: http://nekaka.com/d/6wo0qeVi8O
created by libreoffice 4.1.2.3  (win)

### PR DESCRIPTION
**Pull request by shaforostoff**
tested with an example provided in the issue's comments

### CODE REVIEW

**Comment by unho** [comment]
Can you please add a test for this?

**Comment by unho** [comment]
This was closed by GitHub. Will check it out in a bit.

**Comment by shaforostoff** [comment]
ok, I'm extending an odf test right now

**Comment by shaforostoff** [comment]
i have created a new merge request with additional commit extending odf unit test

**Comment by unho** [comment]
@shaforostoff Thanks a lot, will check https://github.com/translate/translate/pull/3438

**Pull request closed without merging**
