### PR TITLE
Reduce format differences with files saved from Qt Linguist

### PR DESCRIPTION
**Pull request by dg0yt**
Writes the XML declaration with double quotes.
Writes an empty location element.

### CODE REVIEW

**Comment by dg0yt** [comment]
This is a new pull request of previous work in #3443. It turned out that I need to use the integration checks...

The difference which is left open is the handling of '/" vs. &apos;/&quot;.

**Comment by dg0yt** [comment]
Shall I touch the quotes sub-issue, or leave this PR as is? I would use regexps applied on the string from the etree.

**Comment by dwaynebailey** [comment]
@dg0yt feel free to touch, but it might make it easier to PR elsewhere as we're prioritising reviewing your great work here to land.

**Comment by dg0yt** [comment]
I guess I can't easily create another PR because this one might get updated as soon as I commit to my fork - and the new change must depend on those already collected.

**Comment by unho** [comment]
Landed in master. Thanks for the contributions.

**Pull request closed without merging**
