### PR TITLE
Fixing backslash problems for iOS strings

### PR DESCRIPTION
**Pull request by NathanFallet**
Fixing #4617, and then https://github.com/WeblateOrg/weblate/issues/7562

### CODE REVIEW

**Review by nijel — COMMENTED** [review]
You've changed `encode` method which takes care of serializing, but the test covers only parsing. Can you please extend the test to cover serialization as well?

**Comment by NathanFallet** [comment]
You're right, I'm going to add it as well

**Comment by NathanFallet** [comment]
@nijel it's done, you can review again and launch tests if it's okay

**Comment by NathanFallet** [comment]
@nijel it's done, you can review again and launch tests if it's okay.
I've launched tests with and without the modification, and it works as expected (fails without, and succeed with)

**Comment by nijel** [comment]
Merged, thanks for your contribution!

**Pull request merged**
