### PR TITLE
YAML: Fix serialization of empty keys

### PR DESCRIPTION
**Pull request by nijel**
See https://github.com/WeblateOrg/weblate/issues/2128

### CODE REVIEW

**Comment by unho** [comment]
What happens if there are multiple empty keys?

Can you also please add tests for the converters?

**Comment by nijel** [comment]
Multiple same keys are invalid in YAML, so it would fail at parser.

**Comment by nijel** [comment]
I've just added empty keys to the converter tests.

**Comment by unho** [comment]
lgtm @nijel Please land.

**Comment by nijel** [comment]
Thanks for review. Any plans for new release? There are quite a lot fixes accumulated in the master, also see https://github.com/translate/translate/issues/3815

**Pull request merged**
