### PR TITLE
posegment: Japanese test and fix

### PR DESCRIPTION
**Pull request by miurahr**
posegment has unknown bug that fails test that has some complexity.

This test should pass.

It is depend on #3277

### CODE REVIEW

**Comment by friedelwolff** [comment]
As far as I know, posegment only segments if it detects the same number of sentences in both languages. If I read the test correctly, the English has 3 sentences, and the Japanese has four sentences. Although some alignment might be possible, posegment does not implement something advanced enough, and simply refuses to guess. Maybe it can incorporate more advanced sentence alignment methods in future. (I'm writing based on memory, I didn't check the current code.)

**Comment by miurahr** [comment]
Thnak you for your comment. 
I tried simplifying to minimum and found a root cause.

Test case I used is a file download from live example of django documentation.

It includes half width punctuation sign in japanese msgstr.
http://www.unicode.org/charts/PDF/UFF00.pdf

**Comment by miurahr** [comment]
I've add a fix.

**Comment by miurahr** [comment]
This fixes #3280

**Comment by jleclanche** [comment]
lgtm but please squash your test commits

**Comment by unho** [comment]
> This fixes #3280

@miurahr If any of the commits in this PR fixes some issue, can you please update that commit message to include the reference to the issue?

**Comment by unho** [comment]
Merged in 8453724a. Thanks!

**Pull request closed without merging**
