### PR TITLE
Fixed unit equality issue with monolingual units

### LINKED ISSUE #3322: unit equality issue
As the `__ne__` method is not defined for translation units, there is a bug with some unit comparison, for example txt units return True for both `==` and `!=`.
This patch shows the problem when running the test suite:

```diff
diff --git a/translate/storage/test_base.py b/translate/storage/test_base.py
index b65104d..fcf586b 100644
--- a/translate/storage/test_base.py
+++ b/translate/storage/test_base.py
@@ -109,6 +109,7 @@ class TestTranslationUnit:
         assert unit1 != unit3
         assert unit4 != unit5
         assert unit1 != unit6
+        assert not(unit1 == unit6)
 
     def test_target(self):
         unit = self.unit
```

This unexpectedly fails for `TxtUnit`, `RESXUnit`, and `dtdunit`.

We can define the `__ne__` method:

```diff
diff --git a/translate/storage/base.py b/translate/storage/base.py
index b2123b2..22a2bc8 100644
--- a/translate/storage/base.py
+++ b/translate/storage/base.py
@@ -141,6 +141,9 @@ class TranslationUnit(object):
         """
         return self.source == other.source and self.target == other.target
 
+    def __ne__(self, other):
+        return not self.__eq__(other)
+
     def __str__(self):
         """Converts to a string representation that can be parsed back using
         :meth:`~.TranslationStore.parsestring`."""
```

But now `test_eq()` fails, because for some units (mainly monolingual), the source is equal to the target so unit1 and unit6 are indeed identical. I tried to special case the comparison for tests subclassing `TestMonolingualUnit`, but this doesn't seem to be sufficient, as monolingual units are not all behaving the same.

Any pointer from a more experienced dev?

### PR DESCRIPTION
**Pull request by claudep**
Fixes #3322.

### CODE REVIEW

**Comment by unho** [comment]
Just curious why only those monolingual formats needed to be adjusted and all the other monolingual formats don't.

Will merge after some clarification is provided and PR is rebased.

**Comment by claudep** [comment]
Is there somewhere a list of monolingual store types?

**Comment by unho** [comment]
> Is there somewhere a list of monolingual store types?

No, there is not such a list.

- Monolingual formats are: android, catkeys, csv, dtd, html, ical, idml, ini, json, mozilla lang, odf, php, properties, rc, resx, subtitles, txt.
- Not sure about: omegat, oo, symbian, tiki, trados, wordfast, utx.
- Definitely bilingual or multilingual: po, qm, qph, tbx, tmx, ts, xliff.

**Comment by claudep** [comment]
It's either a real problem in the various implementations, or missing tests. However, I'm afraid to be still an inexperienced ttk dev to be able to say much more about this issue.

**Comment by unho** [comment]
I am not sure if there is anybody with enough experience and knowledge of TTK to provide an answer to that question.

**Comment by claudep** [comment]
We could also simply special-case 'RESXUnit', 'dtdunit' and 'TxtUnit' unit classes in the tests. Tests will not pass on Python 3 unless we are fixing this, so someone has to decide something at some point... I don't feel like reimplementing unit classes now.

**Comment by unho** [comment]
Ok, then just merge this PR. Future adjustments, if any, can be proposed in a new PR.

**Comment by claudep** [comment]
Obsoleted by #3342

**Pull request closed without merging**
