### PR TITLE
Skip obsolete units in po2txt

### PR DESCRIPTION
**Pull request by lnussel**

### CODE REVIEW

**Comment by lnussel** [comment]
not sure about your test suite here. A better fix might be to make istranslated() not include obsolete strings. I needed a quick fix for an openSUSE release though. I cannot follow up here.

**Comment by dwaynebailey** [comment]
`istranslatable` should exclude obsolete and header.

**Comment by dwaynebailey** [comment]
@lnussel thanks for the fix, I'll land this with some slight changes and a test as a different PR.

**Comment by dwaynebailey** [comment]
Closing, prefer #3657 fix

**Pull request closed without merging**
