### PR TITLE
chore: Only build docs on change

### PR DESCRIPTION
**Pull request by nschonni**
Skips the build for PRs that don't touch anything related to the docs.

### CODE REVIEW

**Comment by nijel** [comment]
I used to play a lot with filtering, but it comes at cost of not detecting some issues. 

For example, in docs there is:

```rst
.. literalinclude:: ../../tests/cli/example_test.sh
```

So in case this file is removed in the PR, the docs build is skipped and nobody notices that it broke docs. That will be noticed at some point later, either when somebody touches the docs or when releasing. And point of CI is to avoid such errors.

So either you can carefully build the paths list and take extra effor to keep it up to date, or just give up and build the docs on every commit and waste some resources here. In most of my projects I gave up on filtering after being hit by such issues :-).

**Comment by nschonni** [comment]
Thanks, looks like that is the only `literalinclude` in the project.
Looking at it, I think that file could be inlined from the docs. It doesn't really have much that someone wouldn't get from copying another test as a starting point.

**Comment by nschonni** [comment]
I've add that imported file into the globs. i didn't find any others doing the same thing.
Not sure what the failure for codecov is about

**Comment by nijel** [comment]
Merged, thanks for your contribution!

**Pull request merged**
