### PR TITLE
Improved escape and unescape of Android resources with HTML markup

### PR DESCRIPTION
**Pull request by lukakama**
Improved escape and unescape of resources with HTML markup, aligning them to how Android handle them, and adding specific unit tests.

### CODE REVIEW

**Comment by hpatoio** [comment]
If this is working why it's not merged ? @lukakama It's there a way I can use your version on my machine  ?

**Comment by unho** [comment]
@lukakama We are merging the pending PRs in the Toolkit. Can you please rebase this? Thank you very much.

**Comment by lukakama** [comment]
I will try to re-base the PR by the end of this week.

2015-05-05 22:18 GMT+02:00 Leandro Regueiro <notifications@github.com>:

**Comment by unho** [comment]
@lukakama Your rebase was taking too much time, so I cherry-picked and merged in as 6bfbb2cf. Thanks!

**Comment by lukakama** [comment]
Sorry, these days I'm overloaded at work and I had near zero free-time to perform the rebase... However, I'm glad to see that the pull request has been merged anyway :) .

**Pull request closed without merging**
