### PR TITLE
Adding removeuntranslated options to po2json and po2resx

### PR DESCRIPTION
**Pull request by sgarrad**
Refactored po2prop option removeuntranslated into convert.py and added
the ability to remove the values for po2resx and po2json.

### CODE REVIEW

**Comment by unho** [comment]
@sgarrad Please rebase this on top of latest master. Also fix the broken build and split this into separate commits:

* missing fuzzy option in po2resx
* removeuntranslated option

**Comment by unho** [comment]
@sgarrad Don't mind about the missing fuzzy option in po2resx since we already merged that minor change.

**Comment by unho** [comment]
@sgarrad What is the purpose of adding such option to only those commands? And can you please add some tests?

**Comment by sgarrad** [comment]
@unho Only adding them to the po2json and po2resx is based off personal requirement to needing them for only those convertors. However, this can likely be used with any convertor that supports fuzzy matching.

Logic can be different through, for example in the po2prop, the command was already present, however the results are no key or value in the output property file, however, with json and resx for instanace, removing the key and value would likely be bad, so removing the translation i.e. replacing with u"" is a better approach. This also fits in with the existing logic for when content is present/ not present.

I'll add the tests and rebase the commit.

**Comment by sgarrad** [comment]
Not sure, what classes as coverage fail, but I've added tests for both po2resx and po2json for the `--removeuntranslated` option, including rebasing to the latest.

**Comment by DmitryGonchar** [comment]
This option would be useful

**Comment by mkjaxxo** [comment]
Is there a change to get the removeuntranslated options to po2json in the near future? This would be a great enhancement and as DmitryGonchar wrote: Currently untranslated strings will result in empty text in the software instead of the default fallback language.

**Comment by unho** [comment]
> Is there a chance to get the removeuntranslated options to po2json in the near future? This would be a great enhancement and as DmitryGonchar wrote: Currently untranslated strings will result in empty text in the software instead of the default fallback language.

`--removeuntranslated` forces the output to have blank translations instead of falling back to the source text. For example this PO:

```po
#: .stringone
msgid "Foo Bar"
msgstr ""
```

Gets converted to this JSON (uses the original text):

```json
{
    "stringone": "Foo Bar"
} 
```

And with `--removeuntranslated` gets converted to this other JSON (uses blank text):

```json
{
    "stringone": ""
} 
```

@mkjaxxo @DmitryGonchar I certainly don't know your needs (perhaps your JSON translation backend replaces empty translation with the right text), but default current po2json behavior looks sane enough. Anyway I am looking at trying to get this landed.

**Comment by mkjaxxo** [comment]
Thanks for your reply @unho.

Currently we have this source file:

`{
  "id.Name" : "Name",
  "id.Type" : "Type",
  "id.Code" : "Code"
}`

wich results in 

`{
  "id.Name" : "",
  "id.Type" : "translated Type",
  "id.Code" : ""
}`


In the Software, now "" is displayed as id.Name and id.Code and not the source text form the default language. I thought --removeuntranslated would end up in 

`{
  "id.Type" : "translated Type"
}`

**Comment by unho** [comment]
@mkjaxxo Just checked the actual behavior and I thought that the actual output was:

```json
{
  "id.Name" : "Name",
  "id.Type" : "translated Type",
  "id.Code" : "Code"
}
```

but it turns out it is (which is also what `--removeuntranslated` gives us):

```json
{
  "id.Name" : "",
  "id.Type" : "translated Type",
  "id.Code" : ""
}
```

Would be the first result (the one I thought it was outputting) ok for your workflow?

**Comment by unho** [comment]
Just compared this PR and the current behavior of `--removeuntranslated` in other commands, and in other commands it actually removes the fuzzy and untranslated units (outputting only translated units).

**Comment by mkjaxxo** [comment]
Thanks @unho. "remove untranslated" would be perfect. But if po2json would add the source string for untranslated strings to the target file (result 1 from https://github.com/translate/translate/pull/3266#issuecomment-273804377), would be fine too. Way more useful than "blank untranslated".

**Comment by unho** [comment]
@mkjaxxo I have created https://github.com/translate/translate/pull/3549 which add `--removeuntranslated` support for `po2json`. I considered that this close to final 2.0.0 release it is not a good idea to alter the default behavior for `po2json` so it outputs the original source text for untranslated units.

**Comment by unho** [comment]
I am closing this PR since it provides a broken fix. https://github.com/translate/translate/pull/3549 replaces most of it (except the resx part).

**Comment by mkjaxxo** [comment]
Thanks a lot @unho for your work and your support!

**Pull request closed without merging**
