### PR TITLE
Fix Sphinx build errors

### PR DESCRIPTION
**Pull request by nijel**
I've noticed these while working on https://github.com/translate/translate/pull/3674

### CODE REVIEW

**Comment by unho** [comment]
lgtm once Travis passes. Thanks!

**Comment by nijel** [comment]
Hmm, it now only fails a bit later:

```
ImportError: gettext PO library not found
```

**Comment by unho** [comment]
@nijel I wonder if this was brought in after the latest Sphinx version bump.

**Comment by nijel** [comment]
Most likely yes, at least it's now stricter on rst syntax.

**Comment by nijel** [comment]
It seems that libgettextpo-dev is missing on built (probably since Travis upgraded to Trusty).

**Comment by unho** [comment]
lgtm provided https://github.com/translate/translate/commit/11b27712b49f90c6c23abddf03e3067f181eaccd is added back too (sorry about reverting it in master but didn't thought you would go back to this so fast). Also rebase on top of latest master if needed. As usual thanks a lot.

**Comment by nijel** [comment]
Thanks. Rebased and added  11b2771 back, I'll merge once Travis passes.

**Comment by unho** [comment]
Great!

**Pull request merged**
