### PR TITLE
Bump and pin some requirements

### PR DESCRIPTION
**Pull request by unho**

### CODE REVIEW

**Comment by claudep** [comment]
Looks like vobject 0.9.2 supports Python 3. I can have a look if you want.

**Comment by unho** [comment]
@claudep Thanks but it is already on this PR, but somehow messed commits. I am fixing it now.

**Comment by unho** [comment]
No, it seems it is ok.

**Comment by unho** [comment]
> Looks like vobject 0.9.2 supports Python 3. I can have a look if you want.

@claudep It would be great if you can look at the failing tests.

**Comment by claudep** [comment]
vobject upgrade proposed in #3490

**Comment by lnussel** [comment]
Is there a specific reason why six>=1.10.0 is required instead of 1.9 as before?

**Comment by unho** [comment]
This specific requirement was bumped to 1.10.0 only in order to use the latest six version available.

**Comment by lnussel** [comment]
ic. So we will remove that requirement for openSUSE Leap 42.3 as we have six 1.9 there

**Pull request merged**
