### PR TITLE
Refactor pocount

### PR DESCRIPTION
**Pull request by last-partizan**
This splits code into separated stats collection and rendering parse, with each renderer in it's own class.

It should not change any of the outputs, but let's not merge this until #4881 is merged, to be completely safe.

### CODE REVIEW

**Comment by last-partizan** [comment]
This is ready for review now.

Rebased new changes, snapshots of output from the old code and from the new code are identical.

**Comment by last-partizan** [comment]
Next step is to replace hand-written csv with `csv` module, but that will include some changes to the output. So it's better to leave that to another PR.

**Comment by last-partizan** [comment]
@nijel @nschonni Please take a look here.

**Comment by nijel** [comment]
Merged, thanks for your contribution!

**Pull request merged**
