### PR TITLE
remove shebangs from .py files

### PR DESCRIPTION
**Pull request by juhp**
fixes translate/translate#3609

### CODE REVIEW

**Comment by juhp** [comment]
There are a few more matches:

```
tools/mozilla/moz_l10n_builder.py
tools/mozilla/get_moz_enUS.py
tools/mozilla/mozcronbuild.py
tools/mozilla/buildxpi.py
```

though those files seem not installed for me, but I could add them to the PR.

**Comment by phlax** [comment]
@juhp i landed this - and will check out the remaining shebangs - nice one, thanks

**Comment by dwaynebailey** [comment]
@phlax this looks like a good cleanup, I think the ones @juhp excluded might be run in some instances, but they're not installed.

**Comment by juhp** [comment]
Thanks guys! 👍

**Pull request merged**
