### PR TITLE
Update all dependencies and affected functions

### LINKED ISSUE #3843: Make toolkit compatible with diff-match-patch 20181111
As of translate-toolkit 2.3.1, in Arch Linux 64-bit, `po2tmx` and other tools fails with diff-match-patch 20181111 ([site]), because `diff-match-patch==20121119` is required.

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (diff-match-patch 20181111 (/usr/lib/python3.7/site-packages), Requirement.parse('diff-match-patch==20121119'), {'translate-toolkit'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/po2tmx", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 596, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'diff-match-patch==20121119' distribution was not found and is required by translate-toolkit
```

[site]: https://pypi.org/project/diff-match-patch/

### PR DESCRIPTION
**Pull request by vinyldarkscratch**
This PR updates all outdated dependencies and fixes two functions in `translate/lang/data.py` affected by PyCountry's update.

### CODE REVIEW

**Comment by unho** [comment]
@vinyldarkscratch Can you please update this PR to leave out the removal of diff-match-patch?

**Comment by unho** [comment]
Also I am not sure this PR updates all the outdated dependencies as #3833 did.

**Comment by vinyldarkscratch** [comment]
Understood!  I’ll bring back `diff-match-patch` in that case, with version 2018**** (since that’s what pip is downloading anyways, and what’s current, unless 2012**** is strictly required).

As for updating all the dependencies, it should be.  I used requires.io to keep track of what needs updating just like #3833, but I’ll look into it to double-check!  (I’m also creating an updated PR to replace #3833 since the dependency updates also break some of the code, which therefore needs fixing and should be in the same PR.  😛)

**Comment by unho** [comment]
Merged this PR to master after making some adjustments (basically squashing commits and renaming some commits).

Thanks a lot for your contribution!

**Pull request closed without merging**
