### PR TITLE
JSON: keep order when serializing

### LINKED ISSUE #3394: json2po output strings in wrong order
Running `json2po` outputs a valid PO files, but the strings are in the wrong order. I’m not sure exactly *which* order it is, but is *neither* the original order, the reverse order or alphabetically. Here’s an example JSON file:

```json
    {
        "foo": "foo",
        "bar": "bar",
        "baz": "baz"
    }
```

Running `json2po` on this file results in the following (with a PO file header):

```po
    #: .baz
    msgid "baz"
    msgstr ""
    
    #: .foo
    msgid "foo"
    msgstr ""
    
    #: .bar
    msgid "bar"
    msgstr ""
```

Having the strings in a different order than in the original file makes it much harder to correctly translate the file, as one loses context.

I observe this bug both in version 1.13.0 and 1.14.0-rc1.

### PR DESCRIPTION
**Pull request by dwaynebailey**
Followon form 219708fa2d1c44c57aa5eebc8e3edb533d3bdf3e for back conversion.

Fixes #3394

### CODE REVIEW

**Comment by unho** [comment]
lgtm

**Comment by unho** [comment]
Would be nice to document this on dev release notes.

**Comment by dwaynebailey** [comment]
@unho "Unit ordering is maintained" is already in the release notes.  Unless you had some other aspect you felt needed documenting.  I think that is enough.

**Comment by unho** [comment]
@dwaynebailey No, that might be enough. Anyway that will be checked again at release time, as usual. As I said earlier, lgtm.

**Pull request merged**
