### PR TITLE
Add localedir arg to gettext_lang function

### PR DESCRIPTION
**Pull request by phlax**
as the localedir is gotten from `sys.prefix` this was not working inside virtualenvs

### CODE REVIEW

**Comment by unho** [comment]
lgtm

**Comment by unho** [comment]
Alternative approach https://github.com/translate/translate/pull/3636

**Comment by phlax** [comment]
k, but afaict these functions still dont work inside a vm, so they should either be ~fixed or removed i think

**Comment by phlax** [comment]
resolved in other prs

**Pull request closed without merging**
