### PR TITLE
[Blocked by Virtaal] Remove deprecated extractpoline

### PR DESCRIPTION
**Pull request by unho**

### CODE REVIEW

**Comment by unho** [comment]
Virtaal is still using it: https://github.com/translate/virtaal/search?utf8=%E2%9C%93&q=extractpoline

**Comment by nijel** [comment]
Given that Virtaal is anyway broken with current master (lack of Python 3 support), maybe it's time to merge this?

**Comment by unho** [comment]
@friedelwolff See previous comment. If you don't have strong reasons not to we would like to move forward with TTK development.

**Comment by nijel** [comment]
PR fixing this for Virtaal is https://github.com/translate/virtaal/pull/3272

**Pull request merged**
