### PR TITLE
Improve handling of return and array in PHP

### PR DESCRIPTION
**Pull request by nijel**
Improve handling of some corner cases in PHP:

* Correctly serialize [] style arrays
* Correctly parse and serialize return statements

### CODE REVIEW

**Comment by unho** [comment]
My only objection is that docs are not updated despite a new feature of the format is supported now.

**Comment by nijel** [comment]
Both are already covered by the docs. These were working for parsing before, this PR just fixes load/save round trip.

**Comment by unho** [comment]
lgtm

**Comment by nijel** [comment]
Thanks for review.

**Pull request merged**
