### PR TITLE
Appveyor for Windows CI build

### PR DESCRIPTION
**Pull request by nschonni**
Noticed that 2.0 says there is Windows suport, so I thought I'd add in a Windows CI setup.
- The commits haven't been cleaned up/squashed till I saw if there was interested
- Currently has 52 failures https://ci.appveyor.com/project/nschonni/translate/build/1.0.8

This could eventually be used to produce the InnoSetup package for tagged builds and uploaded as an artifact for release attachment.

### CODE REVIEW

**Comment by dwaynebailey** [comment]
@nschonni brilliant :)

Been wanting this for a long time.  Looks like the tests are failing in some Windows specific file access issues and in the code to check cli output.

Not sure how to solve the former.  But the later is probably better served by using pytest-catchlog which can capture stderr and stdout.

Artifacts would be good and would ensure we're actually able to package for Windows users.

**Comment by nschonni** [comment]
Circling back to this to see if I can get a reproduction locally.
- Checked out current master
- Installed everything again (bumped lxml to 3.7.3)
- Installed pytest `html` and `catchlog`
- Got the following errors https://gist.github.com/nschonni/685617d1c2e63ad73c183dbe10fc5a56

I did a weird hack because lxml was giving an error around parsing the xliff XSD, but I put that down to proxy issues since it went away after just copying the xml.xsd locally and updating the import

**Comment by nijel** [comment]
I did rebase this on current master and fixed failing tests in https://github.com/translate/translate/pull/3777

**Comment by nschonni** [comment]
Thanks @nijel, I'll close this one and let you run with yours

**Pull request closed without merging**
