### PR TITLE
ugettext has been renamed on Python 3

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by unho** [comment]
Will merge after rebase.

**Comment by claudep** [comment]
Rebased.

**Comment by unho** [comment]
Merged. Thanks!

**Comment by claudep** [comment]
Nice! Now translate/lang tests are all passing (56) with Python 3.

**Comment by unho** [comment]
So now we still have 1000 failing tests?

**Comment by claudep** [comment]
On my working branch locally, I have ~800 failures remaining, but I have not yet addressed a bunch of str() -> bytes() replacements. The remaining work is hard to estimate, sometimes certain changes are fixing many tests at once...

**Comment by unho** [comment]
You are doing an amazing work here. Let me thank you again.

**Comment by claudep** [comment]
Your review work is very valuable, too! Really appreciated.

**Comment by unho** [comment]
Ok, just throw me more :) Though I will not review more today.

**Pull request merged**
