### PR TITLE
Get web2py converter working and add tests to try to keep it like that.

### LINKED ISSUE #3254: Couple issues with Web2py converter
I just tried using the Web2py converter and it seems to have a couple of issues:
- At first it wouldn't even run because of an unexpected keyword argument (duplicates)
- After changing that to accept **kwargs, I found that it choked on utf-8 strings (in my case, with Umlauts).

In any case, I have made a couple changes and now it works, at least for me - but since I haven't done any proper testing, I don't feel like creating an actual pull request. On the other hand, maybe somebody else can take advantage of this, so here's a gist with the changes I made to web2py2po.py
https://gist.github.com/pgcd/52338762bdcb4728cd39

### PR DESCRIPTION
**Pull request by petterreinholdtsen**
Not quite sure the tests are working yet.

Fixes #3254

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
I would very much like some help with the tests by someone understanding the test machinery.

**Comment by vinyldarkscratch** [comment]
Hey there!  I've actually got web2py2po and po2web2py fixes in #3838 already (though I'm lacking any tests; I assumed there were already some in translate-toolkit), which includes fixes to get the converters working, as well as many needed adjustments like Unicode support.  :wink:

**Comment by petterreinholdtsen** [comment]
Aha.  Perhaps you can update it with the tests I added to my pull request, and then we can close this pull request.  Would be nice if your pull request would close #3254 too.

**Comment by petterreinholdtsen** [comment]
I replaced the code changes in this pull request with the changes from #3838.  The tests fail, no idea why.

**Comment by vinyldarkscratch** [comment]
Looks like it's failing because a .pyc file is being generated: `web2py2po: WARNING: Couldn't handle input file one.pyc: don't know what to do with input format .pyc`

I actually went ahead and [wrote a test file entirely in Python](https://github.com/translate/translate/pull/3838/files#diff-d0454e2bd0610cfaf8858a5e28d4b396) that copies from the po2json test.  This eliminates the dependency on Travis for the tests, allowing the end user to run `python setup.py test` themselves.  All tests now succeed (aside from a small style check, which I just fixed).

**Comment by petterreinholdtsen** [comment]
Right.  As your patch seem to be better than mine, I close this and hope yours will get merged soon.

**Pull request closed without merging**
