### PR TITLE
Replace optparse by argparse

### PR DESCRIPTION
**Pull request by claudep**
Updates and replaces PR #90.

### CODE REVIEW

**Comment by claudep** [comment]
Strangely Travis didn't pick up this one :-(

**Comment by unho** [comment]
@claudep Perhaps use a different branch name. Or try pushing some additional harmless change to this PR. I want tests to pass on Travis before providing any gtm.

**Comment by unho** [comment]
And to be honest I wasn't expecting so many changes after a simple search for "optparse" only returns 8 files: https://github.com/translate/translate/search?utf8=%E2%9C%93&q=optparse

**Comment by claudep** [comment]
Closing to use a different branch name

**Pull request closed without merging**
