### PR TITLE
Replaced dict.iter* by six.iter*(dict)

### PR DESCRIPTION
**Pull request by claudep**
iteritems/iterkeys/itervalues do not exist in Python 3 as it's now
the default method used for iteration by items()/keys()/values().

### CODE REVIEW

**Comment by jleclanche** [comment]
You can probably replace some of those `iteritems()` calls by simple `items()` calls.

**Comment by claudep** [comment]
Sure, but it might be a bit tricky to find those where the iteritems call was purposefully done to prevent a memory issue. Worth the effort?

**Comment by claudep** [comment]
I will still see what I can do and add a complementary commit.

**Comment by claudep** [comment]
I added the commit 6f18aefc3 where I *supposed* it was harmless to do so, after a quick glance. If you find them acceptable, I'll merge the commits.

**Comment by unho** [comment]
IMHO replacing `iteritems()` calls by simple `items()` calls is complicating the review and might have unnoticed performance impact. So please drop the second commit.

@claudep Will merge after dropping the second commit and rebase on top of latest master.

**Comment by claudep** [comment]
Done.

**Comment by unho** [comment]
Merged. Thanks!

**Pull request merged**
