### PR TITLE
[requires.io] dependency update on master branch

### PR DESCRIPTION
**Pull request by unho**

### CODE REVIEW

**Comment by nijel** [comment]
I've just deactivated requires.io, it only breaks things for python < 3.0.

**Comment by unho** [comment]
@nijel Great!

**Comment by unho** [comment]
@nijel Disabling it kinda broke the requirements status flag displayed at top of README. Does dependabot provide an alternative to this?

**Comment by nijel** [comment]
Yes, see https://github.com/translate/translate/pull/3992

**Pull request closed without merging**
