### PR TITLE
YAML converters

### PR DESCRIPTION
**Pull request by unho**

### CODE REVIEW

**Comment by rimas-kudelis** [comment]
What's been holding this one off for so long?

**Comment by unho** [comment]
Rebased on top of latest master and removed the commits were other converters were being refactored, but this still needs more tests before being ready.

**Comment by unho** [comment]
Also need to adjust to support Ruby dialect.

**Comment by rimas-kudelis** [comment]
@unho may I suggest to move Ruby dialect support into its a separate issue/PR?

**Comment by unho** [comment]
Not sure how I messed up merging the PR, but the commits in this PR have been landed.

**Pull request closed without merging**
