### PR TITLE
[requires.io] dependency update on master branch

### PR DESCRIPTION
**Pull request by unho**

### CODE REVIEW

**Comment by nijel** [comment]
Have you considered using [Dependabot](https://github.com/marketplace/dependabot-preview) for bumping dependencies? It automatically creates PR per dependency so that it is easier to see what causes problems and what can be safely merged. It also shows changelog if available, so that you can evaluate the update risk easily as well. It can also optionally automatically merge the PR once all tests pass. 

I have it on Weblate and it works nicely. Example PR: https://github.com/WeblateOrg/docker/pull/589

**Comment by unho** [comment]
No, I haven't considered alternatives. IIRC this is something Dwayne set up. These PRs are automatically created.

**Comment by julen** [comment]
@nijel I ignore how this was setup but I see there's a webhook for requires.io. We can remove that and then you can setup Dependabot; sounds good?

**Comment by nijel** [comment]
@julen Okay, I've just submitted request to @translate to allow Dependabot.

**Pull request closed without merging**
