### PR TITLE
[WIP] Stop ttk from continually trying to import nonsense

### PR DESCRIPTION
**Pull request by phlax**
Hack: cache reimported modules

### CODE REVIEW

**Comment by claudep** [comment]
An alternative could be to use the https://docs.python.org/3/library/functools.html#functools.lru_cache decorator. Django does that, but as it is Python 3-only, a compat file has been added to support Python 2.7 (https://github.com/django/django/blob/master/django/utils/lru_cache.py).

**Comment by phlax** [comment]
@claudep yep - i probably will  - this was a quick hack just to see how it affected timings in pootle tests

I am going to use some kind of registry tho - because this dynamic __import__ pattern doesnt look so good to me

**Comment by nijel** [comment]
As Python 3 is now required, I've implemented it using lru_cache, see https://github.com/translate/translate/pull/4067

**Comment by phlax** [comment]
great, closing in favour of your PR

**Pull request closed without merging**
