### PR TITLE
Add setcontext to mo file

### PR DESCRIPTION
**Pull request by nijel**
It works without problem, just the method is missing.

### CODE REVIEW

**Comment by unho** [comment]
The method is unnecessary. The inherited implementation is just fine. Won't land, but thanks for your contribution. Closing this.

**Comment by nijel** [comment]
Have you tested it? Why do you think that following code (which is inherited) will work? It doesn't store the context at all...

```
    def setcontext(self, context):
        """Set the message context"""
        pass
```

**Comment by unho** [comment]
No, it doesn't store the context, but I don't think it is necessary to.

**Comment by nijel** [comment]
So it's okay to have setcontext which does nothing and fiddle with msgctx directly?

**Comment by nijel** [comment]
In such case I'd rather suggest to remove setcontext from the base class if it's not intended as generic API.

Anyway I've updated my branch to be based on current master and added testcase for this.

**Pull request closed without merging**
