### PR TITLE
Update jsonl10n.py

### PR DESCRIPTION
**Pull request by EmilTemirov**
Added ability to parse ES6 based js translation.

### CODE REVIEW

**Comment by unho** [comment]
Please add some tests in `translate/storage/test_jsonl10n.py`. Also please squash the commits and rebase on top of latest master.

**Comment by unho** [comment]
@EmilTemirov Why did you close this pull request?

**Comment by EmilTemirov** [comment]
@unho I figured out that ES6 based js translation is fundamentally different than JSON file. I wanted to integrate Translate Toolkit with https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Defining-Translations but in this case, you have no restrictions on the format of your translations.js file. As you can see in examples, there are used single quotes for keys and values that are not correctly for JSON format. 
I found another solution for my project (http://i18next.com/translate/) that supports JSON for translations.

**Comment by unho** [comment]
Actually that is not a translation format, but JavaScript code. The translations are defined in a way that looks like JSON. Probably TTK would work with your patch, so did you actually tried to use it?

**Comment by EmilTemirov** [comment]
Yes, I did. It works but you should remember about double quotes... Otherwise, you will get a JSON Parse exception.

**Pull request closed without merging**
