### PR TITLE
CLDR & Gwt properties file handling

### PR DESCRIPTION
**Pull request by diorcety**
It's not clean commits but it's just for the idea.

Currently the order of plural forms is the one from gettext and there is no way to know which plural form is the first,second, entry in the multistring.

In GWT the plural forms are derived from CLDR. This pull request introduce some CLDR mapping.
for example:

```
'fr': (u'French', 2, '(n > 1)', ['one', 'other']),
'ar': (u'Arabic', 6, 'n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 ? 4 : 5', ['zero', 'one', 'two', 'few', 'many', 'other']),
```

Lot of mappings are missing
Which this mapping we can identify each plural forms and convert this forms in GWT properties format

This pull request is linked to another Pootle pull request (less linked to GWT stuff)

### CODE REVIEW

**Comment by unho** [comment]
@diorcety  Hi, I have several concerns:

* Can you please rebase this PR on top of latest master?
* Can you please expand the descriptions in the commit messages so they tell the reason or purpose of the commit?
* Can CLDR and gwt changes be landed independently as separate PRs?
* Can commit c2b557aa be landed as a separate PR?
* Can commit 65f6e3f1 be landed as a separate PR?
* What is gwt?
* Can you please provide references to gwt format particularities?
* Can you please expand docs on properties to tell about gwt?

**Comment by diorcety** [comment]
Hi
It will be not possible for tonight. You merge lot of code from another source. Seems really difficult to reuse my changes.

The main goal of this patches is to support gwt translation files. It just a java .properties file with UTF-8 native handling and plurials form like key[form] = text

Regards,

**Comment by unho** [comment]
@diorcety Our apologies for the rush. Maybe you can polish it so it can be merged in the following days or weeks. We will try to merge it ASAP. Obviously it is not going to be in the next release, but maybe on the following one.

**Comment by jleclanche** [comment]
@diorcety can you attach (on gist.github.com or some such) an example GWT properties file please?

**Comment by diorcety** [comment]
http://www.gwtproject.org/doc/latest/DevGuideI18nPluralForms.html

**Comment by diorcety** [comment]
Hi,
I look back the code. it could be easy to rebase it (i mix with the pootle PR).
The main issue is that i have introduce a proppluralunit in order to keep a trace of the cdlr mapping. Not really beautiful but that the only thing that i succeed to do.

**Comment by diorcety** [comment]
And yes the cdlr need to be completed

**Comment by unho** [comment]
@diorcety We have just released Translate Toolkit 1.13.0. We would to include these changes (or at least part of them) in the next release. No need to rush but the sooner this gets in shape (preferably in several separate PRs) the sooner it will get merged.

**Comment by diorcety** [comment]
Ok i will do this next weeks.

**Comment by diorcety** [comment]
I have created an issue about CLDR(#3271). I need feedback in order to have a complete support of all language in this PR

**Comment by unho** [comment]
@diorcety Please rebase this PR on top of latest master. A lot of stuff changed on master lately.

**Comment by diorcety** [comment]
Replaced by #3885

**Pull request closed without merging**
